training_data = [

    # ================= TRACK =================
    ("Where is my order?", "Track"),
    ("Track my package", "Track"),
    ("Where is my package?", "Track"),
    ("My parcel hasn't arrived", "Track"),
    ("Track my order", "Track"),
    ("Order status", "Track"),
    ("Where's my parcel?", "Track"),
    ("Has my order shipped?", "Track"),
    ("Did my order ship?", "Track"),
    ("When will my package arrive?", "Track"),
    ("Where is my delivery?", "Track"),
    ("Can you track my order?", "Track"),
    ("I want to track my package", "Track"),
    ("Show my tracking details", "Track"),
    ("Track shipment", "Track"),
    ("Package status", "Track"),
    ("Delivery status", "Track"),
    ("Check my order", "Track"),
    ("Check delivery", "Track"),
    ("My order is late", "Track"),
    ("My package is delayed", "Track"),
    ("Still waiting for my order", "Track"),
    ("I haven't received my package", "Track"),
    ("Where did my package go?", "Track"),
    ("Find my package", "Track"),
    ("Locate my order", "Track"),
    ("Track delivery", "Track"),
    ("Any update on my order?", "Track"),
    ("When is my order coming?", "Track"),
    ("Is my package on the way?", "Track"),

    # ================= REFUND =================
    ("I want a refund", "Refund"),
    ("Return my money", "Refund"),
    ("Give my money back", "Refund"),
    ("Refund my payment", "Refund"),
    ("I need a refund", "Refund"),
    ("Refund please", "Refund"),
    ("Can I get my money back?", "Refund"),
    ("I changed my mind", "Refund"),
    ("Refund this order", "Refund"),
    ("I don't want it anymore", "Refund"),
    ("The product is damaged", "Refund"),
    ("The item arrived broken", "Refund"),
    ("Wrong product received", "Refund"),
    ("The order is defective", "Refund"),
    ("I want my payment back", "Refund"),
    ("Please refund me", "Refund"),
    ("Can you refund me?", "Refund"),
    ("Request a refund", "Refund"),
    ("I need my money back", "Refund"),
    ("Issue a refund", "Refund"),
    ("Refund my order", "Refund"),
    ("Refund my purchase", "Refund"),
    ("I'd like a refund", "Refund"),
    ("Reverse my payment", "Refund"),
    ("I want to return this item", "Refund"),
    ("Refund this purchase", "Refund"),
    ("Money back please", "Refund"),
    ("Please return my money", "Refund"),
    ("How do I get a refund?", "Refund"),
    ("Can I return this product?", "Refund"),

    # ================= CANCEL =================
    ("Cancel my order", "Cancel"),
    ("Delete my order", "Cancel"),
    ("Stop my order", "Cancel"),
    ("I don't want this order", "Cancel"),
    ("Cancel it", "Cancel"),
    ("Please cancel my purchase", "Cancel"),
    ("Cancel the shipment", "Cancel"),
    ("I ordered by mistake", "Cancel"),
    ("Don't send my order", "Cancel"),
    ("Cancel before shipping", "Cancel"),
    ("I changed my mind", "Cancel"),
    ("Remove my order", "Cancel"),
    ("End my order", "Cancel"),
    ("Cancel this purchase", "Cancel"),
    ("Can you cancel it?", "Cancel"),
    ("I'd like to cancel", "Cancel"),
    ("Please stop the order", "Cancel"),
    ("Do not ship my order", "Cancel"),
    ("Abort my order", "Cancel"),
    ("Close my order", "Cancel"),
    ("I no longer want this", "Cancel"),
    ("Cancel everything", "Cancel"),
    ("Can I cancel my order?", "Cancel"),
    ("Undo my order", "Cancel"),
    ("Withdraw my order", "Cancel"),
    ("Stop processing my order", "Cancel"),
    ("Don't deliver it", "Cancel"),
    ("Please remove my purchase", "Cancel"),
    ("Cancel the transaction", "Cancel"),
    ("I don't need it anymore", "Cancel"),

    # ================= PASSWORD =================
    ("I forgot my password", "Password"),
    ("Reset my password", "Password"),
    ("Can't login", "Password"),
    ("Help me login", "Password"),
    ("Forgot password", "Password"),
    ("Password reset", "Password"),
    ("I can't sign in", "Password"),
    ("Unable to login", "Password"),
    ("Login failed", "Password"),
    ("Recover my account", "Password"),
    ("Recover password", "Password"),
    ("Forgot my login", "Password"),
    ("Need a new password", "Password"),
    ("Change my password", "Password"),
    ("Update my password", "Password"),
    ("Password isn't working", "Password"),
    ("My password is incorrect", "Password"),
    ("Help me access my account", "Password"),
    ("I can't access my account", "Password"),
    ("Reset login credentials", "Password"),
    ("Unlock my account", "Password"),
    ("Can't remember my password", "Password"),
    ("Forgot my account password", "Password"),
    ("Login problem", "Password"),
    ("Sign in issue", "Password"),
    ("Need help signing in", "Password"),
    ("Password help", "Password"),
    ("How do I reset my password?", "Password"),
    ("I lost my password", "Password"),
    ("My account is locked", "Password"),
]
