training_data = [

("bro really thought that would work", "Funny"),
("my laptop started sounding like a helicopter after opening two tabs", "Funny"),
("the bug fixed itself and now i'm scared to touch the code", "Funny"),
("this update was tested by nobody", "Funny"),
("the tutorial boss was harder than the final boss", "Funny"),
("my internet disconnects only when i'm winning", "Funny"),
("he studied the day after the exam", "Funny"),
("that plan had zero chance of succeeding", "Funny"),
("my code is held together by hope", "Funny"),
("the compiler accepted my apology instead of my code", "Funny"),
("bro lost an argument to autocorrect", "Funny"),
("that notification gave me emotional damage", "Funny"),
("the loading screen has become my home", "Funny"),
("he missed the point so hard it became a new point", "Funny"),
("my alarm clock works harder than i do", "Funny"),
("the group project became a solo project in disguise", "Funny"),
("he typed confidently and still got everything wrong", "Funny"),
("the server chose violence today", "Funny"),
("my keyboard has trust issues now", "Funny"),
("the bug reproduced faster than rabbits", "Funny"),
("he speedran embarrassment", "Funny"),
("that excuse expired before you said it", "Funny"),
("my battery dies out of pure disrespect", "Funny"),
("the assignment looked back at me", "Funny"),
("he installed confidence instead of skill", "Funny"),
("the AI answered everything except the question", "Funny"),
("my phone froze at the perfect moment", "Funny"),
("that meeting could have been an email", "Funny"),
("he pressed random buttons and called it debugging", "Funny"),
("the printer woke up angry", "Funny"),
("that idea should have stayed in drafts", "Funny"),
("my browser collected tabs like trophies", "Funny"),
("he challenged reality and lost", "Funny"),
("the coffee stopped working halfway through the assignment", "Funny"),
("my code compiled out of pity", "Funny"),
("he celebrated before checking the results", "Funny"),
("that password was stronger than my willpower", "Funny"),
("the deadline appeared out of nowhere", "Funny"),
("my chair knows all my bad decisions", "Funny"),
("the update fixed one bug and unlocked five more", "Funny"),
("he googled the question and got more confused", "Funny"),
("my storage disappeared without downloading anything", "Funny"),
("that strategy had the lifespan of a soap bubble", "Funny"),
("he treated stack overflow like a religion", "Funny"),
("my wifi takes lunch breaks", "Funny"),
("the error message had more confidence than i do", "Funny"),
("he forgot why he entered the room", "Funny"),
("my computer restarted to avoid responsibility", "Funny"),
("that shortcut created a longer route", "Funny"),
("the microphone worked only after the meeting ended", "Funny"),
("he trusted the first result on the internet", "Funny"),
("my notes looked like ancient scripture", "Funny"),
("the project manager discovered a new deadline", "Funny"),
("he turned one bug into downloadable content", "Funny"),
("my phone waited until one percent to become useful", "Funny"),
("that fix was temporary for exactly three seconds", "Funny"),
("the calculator judged my math", "Funny"),
("he tried to multitask and achieved nothing twice as fast", "Funny"),
("my brain opened too many background processes", "Funny"),
("the exam asked questions from another universe", "Funny"),
("he clicked accept without reading anything", "Funny"),
("my code passed every test except the important one", "Funny"),
("the coffee machine resigned", "Funny"),
("he found a shortcut that took longer", "Funny"),
("my headphones disconnected at the worst possible time", "Funny"),
("the bug had plot armor", "Funny"),
("he upgraded everything except common sense", "Funny"),
("my browser crashed under emotional pressure", "Funny"),
("that email could have stayed unsent forever", "Funny"),
("the app updated just to change the icon", "Funny"),
("he made a backup after deleting everything", "Funny"),
("my search history deserves witness protection", "Funny"),
("the charger only works at one specific angle", "Funny"),
("he spent an hour fixing a typo", "Funny"),
("my motivation left without notice", "Funny"),
("that feature exists only in the documentation", "Funny"),
("he solved the wrong problem perfectly", "Funny"),
("the internet disappeared during the presentation", "Funny"),
("my computer became philosophical during startup", "Funny"),
("that was a premium quality bad idea", "Funny"),
("he accidentally created a new problem while solving another", "Funny"),
("my RAM entered early retirement", "Funny"),
("the meeting had side quests", "Funny"),
("he treated guessing like a strategy", "Funny"),
("my phone survived everything except the floor", "Funny"),
("that screenshot raised more questions than answers", "Funny"),
("he wrote comments that confused future him", "Funny"),
("my download speed entered slow motion", "Funny"),
("the software update required another software update", "Funny"),
("he found the only impossible option", "Funny"),
("my calculator needed a calculator", "Funny"),
("that decision aged instantly", "Funny"),
("he practiced confidence instead of competence", "Funny"),
("my desktop has become a museum of screenshots", "Funny"),
("the game rewarded failure with another failure", "Funny"),
("he debugged for two hours before turning the computer on", "Funny"),
("my inbox is a horror story", "Funny"),
("the loading bar stopped to think", "Funny"),
("he somehow made copy and paste difficult", "Funny"),
("my password manager forgot my password", "Funny"),
("that bug has been promoted to a feature", "Funny"),
("he invented extra work by accident", "Funny"),
("my code is running entirely on luck", "Funny")


("I'm going to the grocery store later.", "Normal"),
("Can you help me with this Python code?", "Normal"),
("I finished my homework this morning.", "Normal"),
("What's your favorite programming language?", "Normal"),
("I'll call you after dinner.", "Normal"),
("The weather looks nice today.", "Normal"),
("I'm thinking about buying a new laptop.", "Normal"),
("Have you watched the new movie yet?", "Normal"),
("Let's meet around 6 PM.", "Normal"),
("I need to charge my phone.", "Normal"),
("I'm learning machine learning.", "Normal"),
("Can you explain recursion?", "Normal"),
("The update looks pretty good.", "Normal"),
("I'm working on a side project.", "Normal"),
("This game is surprisingly fun.", "Normal"),
("I have an exam next week.", "Normal"),
("Coffee helps me stay awake.", "Normal"),
("I'm trying to improve my coding skills.", "Normal"),
("The internet is a little slow today.", "Normal"),
("I forgot to reply to that message.", "Normal"),
("I usually wake up around seven.", "Normal"),
("This keyboard feels comfortable.", "Normal"),
("I need to clean my desk.", "Normal"),
("The project is almost finished.", "Normal"),
("I'm reading a new book.", "Normal"),
("Can you send me the file?", "Normal"),
("My headphones need charging.", "Normal"),
("I'm planning a weekend trip.", "Normal"),
("The food was really good.", "Normal"),
("I have a meeting this afternoon.", "Normal"),
("The battery lasts all day.", "Normal"),
("I'm watching a tutorial.", "Normal"),
("The room is a bit cold.", "Normal"),
("I enjoy solving programming problems.", "Normal"),
("The bus arrived on time.", "Normal"),
("I need to update my resume.", "Normal"),
("My computer is running smoothly.", "Normal"),
("I'll finish it tomorrow.", "Normal"),
("The assignment wasn't too difficult.", "Normal"),
("I like listening to music while studying.", "Normal"),
("Can you recommend a good book?", "Normal"),
("I ordered lunch online.", "Normal"),
("The presentation went well.", "Normal"),
("I forgot my charger at home.", "Normal"),
("The app is easy to use.", "Normal"),
("I need a short break.", "Normal"),
("The meeting ended early.", "Normal"),
("I'm saving money for a new PC.", "Normal"),
("This café has great coffee.", "Normal"),
("I finally organized my files.", "Normal"),
("I'm practicing English every day.", "Normal"),
("My phone storage is almost full.", "Normal"),
("The movie was better than I expected.", "Normal"),
("I finished reading the article.", "Normal"),
("I'm interested in artificial intelligence.", "Normal"),
("Can we reschedule the meeting?", "Normal"),
("The train was a few minutes late.", "Normal"),
("I'm learning how to build websites.", "Normal"),
("I like walking in the evening.", "Normal"),
("This chair is comfortable.", "Normal"),
("I installed the latest update.", "Normal"),
("The documentation was helpful.", "Normal"),
("I usually study at night.", "Normal"),
("I'm thinking about starting a business.", "Normal"),
("The lecture was interesting.", "Normal"),
("My desk is finally clean.", "Normal"),
("I need to drink more water.", "Normal"),
("The website loads quickly.", "Normal"),
("I'm looking for a good internship.", "Normal"),
("I enjoy playing strategy games.", "Normal"),
("The weather might change tomorrow.", "Normal"),
("I'm testing a new feature.", "Normal"),
("The package arrived today.", "Normal"),
("I forgot my notebook.", "Normal"),
("Can you review my project?", "Normal"),
("I'm waiting for the download to finish.", "Normal"),
("The class starts at nine.", "Normal"),
("I have a lot of work today.", "Normal"),
("This monitor has great colors.", "Normal"),
("I learned something new today.", "Normal"),
("The server is running normally.", "Normal"),
("I need more practice.", "Normal"),
("The room is quiet.", "Normal"),
("I'm planning my schedule.", "Normal"),
("The update fixed several issues.", "Normal"),
("I enjoy learning new technologies.", "Normal"),
("The coffee is still hot.", "Normal"),
("I'll send it when I'm done.", "Normal"),
("The keyboard has good key travel.", "Normal"),
("I started a new course yesterday.", "Normal"),
("The file has been uploaded.", "Normal"),
("I'm working from home today.", "Normal"),
("This tutorial explains everything clearly.", "Normal"),
("I have enough time to finish.", "Normal"),
("The internet connection is stable.", "Normal"),
("My alarm went off early.", "Normal"),
("The project is making good progress.", "Normal"),
("I'm organizing my workspace.", "Normal"),
("This software is easy to learn.", "Normal"),
("I need to back up my files.", "Normal"),
("The code is much cleaner now.", "Normal")

    ("The sky is blue.", "Dead"),
    ("Water is a liquid.", "Dead"),
    ("Fire is hot.", "Dead"),
    ("Ice is cold.", "Dead"),
    ("The Earth revolves around the Sun.", "Dead"),
    ("The Moon orbits the Earth.", "Dead"),
    ("A square has four sides.", "Dead"),
    ("A triangle has three sides.", "Dead"),
    ("Most birds have feathers.", "Dead"),
    ("Fish live in water.", "Dead"),
    ("Trees have leaves.", "Dead"),
    ("Grass is green.", "Dead"),
    ("The Sun rises in the east.", "Dead"),
    ("The Sun sets in the west.", "Dead"),
    ("People breathe air.", "Dead"),
    ("Cars have wheels.", "Dead"),
    ("Bicycles have two wheels.", "Dead"),
    ("Books contain pages.", "Dead"),
    ("Pens are used for writing.", "Dead"),
    ("Pencils can be sharpened.", "Dead"),
    ("Computers use electricity.", "Dead"),
    ("Phones can make calls.", "Dead"),
    ("Laptops have screens.", "Dead"),
    ("Keyboards have keys.", "Dead"),
    ("A mouse can control a cursor.", "Dead"),
    ("Monitors display images.", "Dead"),
    ("Doors can be opened.", "Dead"),
    ("Windows are made of glass.", "Dead"),
    ("Chairs are used for sitting.", "Dead"),
    ("Tables have legs.", "Dead"),
    ("Shoes are worn on feet.", "Dead"),
    ("Hats are worn on the head.", "Dead"),
    ("Socks come in pairs.", "Dead"),
    ("Rain falls from clouds.", "Dead"),
    ("Snow is frozen water.", "Dead"),
    ("Clouds are in the sky.", "Dead"),
    ("Mountains are higher than hills.", "Dead"),
    ("Rivers contain water.", "Dead"),
    ("Oceans are large bodies of water.", "Dead"),
    ("Sand is made of small particles.", "Dead"),
    ("Paper is made from wood.", "Dead"),
    ("Plastic is a material.", "Dead"),
    ("Metal is solid.", "Dead"),
    ("Glass can break.", "Dead"),
    ("Wood comes from trees.", "Dead"),
    ("Milk is a drink.", "Dead"),
    ("Bread is a type of food.", "Dead"),
    ("Rice is commonly eaten.", "Dead"),
    ("Fruit grows on plants.", "Dead"),
    ("Vegetables are edible.", "Dead"),
    ("Dogs are animals.", "Dead"),
    ("Cats are mammals.", "Dead"),
    ("Elephants are large animals.", "Dead"),
    ("Birds can lay eggs.", "Dead"),
    ("Most insects have six legs.", "Dead"),
    ("Spiders have eight legs.", "Dead"),
    ("Bees make honey.", "Dead"),
    ("The alphabet contains letters.", "Dead"),
    ("Numbers are used for counting.", "Dead"),
    ("Time is measured with clocks.", "Dead"),
    ("A year has twelve months.", "Dead"),
    ("A week has seven days.", "Dead"),
    ("A day has twenty-four hours.", "Dead"),
    ("An hour has sixty minutes.", "Dead"),
    ("A minute has sixty seconds.", "Dead"),
    ("Schools have classrooms.", "Dead"),
    ("Teachers teach students.", "Dead"),
    ("Students attend classes.", "Dead"),
    ("Hospitals treat patients.", "Dead"),
    ("Doctors work in healthcare.", "Dead"),
    ("Nurses care for patients.", "Dead"),
    ("Libraries contain books.", "Dead"),
    ("Roads connect places.", "Dead"),
    ("Bridges cross rivers.", "Dead"),
    ("Airplanes can fly.", "Dead"),
    ("Boats travel on water.", "Dead"),
    ("Trains run on tracks.", "Dead"),
    ("Buses carry passengers.", "Dead"),
    ("Traffic lights control traffic.", "Dead"),
    ("Maps show locations.", "Dead"),
    ("Coins are a form of money.", "Dead"),
    ("Banks store money.", "Dead"),
    ("Stores sell products.", "Dead"),
    ("Markets have customers.", "Dead"),
    ("Batteries store energy.", "Dead"),
    ("Lights produce illumination.", "Dead"),
    ("Fans move air.", "Dead"),
    ("Heaters produce heat.", "Dead"),
    ("Refrigerators keep food cold.", "Dead"),
    ("Ovens are used for baking.", "Dead"),
    ("Cups can hold liquids.", "Dead"),
    ("Plates are used for food.", "Dead"),
    ("Forks are eating utensils.", "Dead"),
    ("Spoons are used for eating.", "Dead"),
    ("Knives can cut food.", "Dead"),
    ("Soap is used for cleaning.", "Dead"),
    ("Water can be frozen.", "Dead"),
    ("Computers process data.", "Dead"),
    ("Software runs on hardware.", "Dead"),
    ("Files can be saved.", "Dead"),
    ("The internet connects computers.", "Dead"),
    ("Today is today.", "Dead"),
    ("Tomorrow comes after today.", "Dead")


]