training_data = [

    # 👋 Greeting
    ("Hello", "Greeting"),
    ("Hi", "Greeting"),
    ("Hey", "Greeting"),
    ("Good morning", "Greeting"),
    ("Good afternoon", "Greeting"),
    ("Good evening", "Greeting"),
    ("How are you", "Greeting"),
    ("Nice to meet you", "Greeting"),
    ("Hi there", "Greeting"),
    ("Greetings", "Greeting"),
    ("What's up", "Greeting"),
    ("Yo", "Greeting"),
    ("Good to see you", "Greeting"),
    ("Hello friend", "Greeting"),
    ("Hey buddy", "Greeting"),
    ("Morning", "Greeting"),
    ("Evening", "Greeting"),
    ("Hi assistant", "Greeting"),
    ("Hello there", "Greeting"),
    ("Hey there", "Greeting"),

    # 🍕 Food
    ("Order pizza", "Food"),
    ("I want pizza", "Food"),
    ("Buy pizza", "Food"),
    ("I want burger", "Food"),
    ("Order burger", "Food"),
    ("Buy sushi", "Food"),
    ("I want sushi", "Food"),
    ("Order pasta", "Food"),
    ("Get me noodles", "Food"),
    ("I am hungry", "Food"),
    ("Find food nearby", "Food"),
    ("Order dinner", "Food"),
    ("Order lunch", "Food"),
    ("Order breakfast", "Food"),
    ("Get me a sandwich", "Food"),
    ("Buy fries", "Food"),
    ("I want to eat", "Food"),
    ("Order tacos", "Food"),
    ("Get me some food", "Food"),
    ("Order chicken", "Food"),

    # ✈️ Travel
    ("Book a flight", "Travel"),
    ("I need a ticket", "Travel"),
    ("Find flights to Delhi", "Travel"),
    ("Book hotel", "Travel"),
    ("Reserve a hotel", "Travel"),
    ("Search flights", "Travel"),
    ("Find train tickets", "Travel"),
    ("Book bus tickets", "Travel"),
    ("Plan my trip", "Travel"),
    ("Travel to Mumbai", "Travel"),
    ("Book my vacation", "Travel"),
    ("Show cheap flights", "Travel"),
    ("Find hotels nearby", "Travel"),
    ("Book train", "Travel"),
    ("Book bus", "Travel"),
    ("Need a flight tomorrow", "Travel"),
    ("Travel to Bangalore", "Travel"),
    ("Find travel deals", "Travel"),
    ("Reserve flight", "Travel"),
    ("Find places to stay", "Travel"),

    # 💸 Refund
    ("I want a refund", "Refund"),
    ("Return my money", "Refund"),
    ("Cancel my order", "Refund"),
    ("Refund this purchase", "Refund"),
    ("Give my money back", "Refund"),
    ("I want to return this", "Refund"),
    ("Cancel my purchase", "Refund"),
    ("Refund my payment", "Refund"),
    ("I changed my mind", "Refund"),
    ("I don't want this anymore", "Refund"),
    ("Return this item", "Refund"),
    ("Refund my order", "Refund"),
    ("Cancel this product", "Refund"),
    ("Refund please", "Refund"),
    ("I'd like a refund", "Refund"),
    ("Take this back", "Refund"),
    ("Reverse the payment", "Refund"),
    ("Cancel the booking", "Refund"),
    ("I need my money back", "Refund"),
    ("Refund the transaction", "Refund"),

    # 🎵 Music
    ("Play music", "Music"),
    ("Play a song", "Music"),
    ("Pause music", "Music"),
    ("Resume music", "Music"),
    ("Next song", "Music"),
    ("Previous song", "Music"),
    ("Increase volume", "Music"),
    ("Lower the volume", "Music"),
    ("Play my playlist", "Music"),
    ("Shuffle songs", "Music"),
    ("Stop music", "Music"),
    ("Play rock music", "Music"),
    ("Play pop songs", "Music"),
    ("Play relaxing music", "Music"),
    ("Play jazz", "Music"),
    ("Mute music", "Music"),
    ("Unmute music", "Music"),
    ("Repeat this song", "Music"),
    ("Play my favorite song", "Music"),
    ("Start the music", "Music"),

    # ⏰ Alarm
    ("Set an alarm", "Alarm"),
    ("Wake me at 7 AM", "Alarm"),
    ("Alarm for tomorrow", "Alarm"),
    ("Create an alarm", "Alarm"),
    ("Cancel my alarm", "Alarm"),
    ("Delete alarm", "Alarm"),
    ("Alarm at 6", "Alarm"),
    ("Wake me up", "Alarm"),
    ("Set alarm for 8 PM", "Alarm"),
    ("Morning alarm", "Alarm"),
    ("Evening alarm", "Alarm"),
    ("Turn off alarm", "Alarm"),
    ("Enable alarm", "Alarm"),
    ("Alarm for Monday", "Alarm"),
    ("Alarm after 30 minutes", "Alarm"),
    ("Set daily alarm", "Alarm"),
    ("Remind me tomorrow morning", "Alarm"),
    ("Set wake up alarm", "Alarm"),
    ("Alarm at 5 AM", "Alarm"),
    ("Create wake up alarm", "Alarm"),

    # 🧮 Calculator
    ("What is 2 plus 2", "Calculator"),
    ("Calculate 5 times 8", "Calculator"),
    ("100 divided by 5", "Calculator"),
    ("10 minus 3", "Calculator"),
    ("Square root of 81", "Calculator"),
    ("What is 25 plus 18", "Calculator"),
    ("Multiply 9 by 6", "Calculator"),
    ("Add these numbers", "Calculator"),
    ("Solve this math", "Calculator"),
    ("Calculate percentage", "Calculator"),
    ("20 plus 50", "Calculator"),
    ("15 times 12", "Calculator"),
    ("7 multiplied by 8", "Calculator"),
    ("Divide 90 by 9", "Calculator"),
    ("Calculate 1000 minus 450", "Calculator"),
    ("What is 99 plus 1", "Calculator"),
    ("Find the answer", "Calculator"),
    ("Do the math", "Calculator"),
    ("Calculate 45 plus 33", "Calculator"),
    ("Compute 18 times 4", "Calculator"),

    # ☀️ Weather
    ("What's the weather today", "Weather"),
    ("Will it rain today", "Weather"),
    ("Is it sunny", "Weather"),
    ("Weather forecast", "Weather"),
    ("Today's temperature", "Weather"),
    ("Is it hot outside", "Weather"),
    ("Is it cold today", "Weather"),
    ("Weather tomorrow", "Weather"),
    ("Will it snow", "Weather"),
    ("Chance of rain", "Weather"),
    ("Current weather", "Weather"),
    ("How windy is it", "Weather"),
    ("Humidity today", "Weather"),
    ("Show weather", "Weather"),
    ("Weather in Delhi", "Weather"),
    ("Weather in Mumbai", "Weather"),
    ("Do I need an umbrella", "Weather"),
    ("Forecast for this week", "Weather"),
    ("Is it cloudy", "Weather"),
    ("Temperature outside", "Weather"),

    # 📰 News
    ("Show today's news", "News"),
    ("Latest news", "News"),
    ("Breaking news", "News"),
    ("Technology news", "News"),
    ("Sports news", "News"),
    ("Business news", "News"),
    ("Political news", "News"),
    ("World news", "News"),
    ("Science news", "News"),
    ("Entertainment news", "News"),
    ("Top headlines", "News"),
    ("Current news", "News"),
    ("What's happening today", "News"),
    ("Latest updates", "News"),
    ("News about AI", "News"),
    ("Health news", "News"),
    ("Finance news", "News"),
    ("Local news", "News"),
    ("International news", "News"),
    ("Show me the headlines", "News"),

    # 👋 Greeting
    ("Good day", "Greeting"),
    ("Howdy", "Greeting"),
    ("Hey, how's it going?", "Greeting"),
    ("Hope you're doing well", "Greeting"),
    ("Hi, can you help me?", "Greeting"),
    ("Hello assistant", "Greeting"),
    ("Hey AI", "Greeting"),
    ("Nice to see you", "Greeting"),
    ("How have you been?", "Greeting"),
    ("Long time no see", "Greeting"),
    ("Good to have you here", "Greeting"),
    ("Hello, what's new?", "Greeting"),
    ("Hey there!", "Greeting"),
    ("Hi again", "Greeting"),
    ("Pleasure to meet you", "Greeting"),
    ("What's going on?", "Greeting"),
    ("Hope you're having a good day", "Greeting"),
    ("Hey, are you there?", "Greeting"),
    ("Hi!", "Greeting"),
    ("Hello!", "Greeting"),

    # 🍕 Food
    ("I'm craving pizza", "Food"),
    ("Can you order some food?", "Food"),
    ("I'd like to order dinner", "Food"),
    ("Get me something to eat", "Food"),
    ("Order a cheese pizza", "Food"),
    ("I feel like eating burgers", "Food"),
    ("Can I get some sushi?", "Food"),
    ("Order Chinese food", "Food"),
    ("I want a sandwich", "Food"),
    ("Let's order lunch", "Food"),
    ("Get me fried rice", "Food"),
    ("I'm hungry, order food", "Food"),
    ("Can you buy me a pizza?", "Food"),
    ("Order some snacks", "Food"),
    ("I want ice cream", "Food"),
    ("Buy me a burger", "Food"),
    ("Get me a coffee", "Food"),
    ("Order biryani", "Food"),
    ("I'd like some pasta", "Food"),
    ("Can you order tacos?", "Food"),

    # ✈️ Travel
    ("I want to travel to Goa", "Travel"),
    ("Find me a hotel", "Travel"),
    ("Book a room for tonight", "Travel"),
    ("Search for flights to Mumbai", "Travel"),
    ("I need a hotel in Delhi", "Travel"),
    ("Show me cheap hotels", "Travel"),
    ("I need to catch a flight", "Travel"),
    ("Find flights for tomorrow", "Travel"),
    ("Book my vacation package", "Travel"),
    ("Reserve a seat on the train", "Travel"),
    ("Help me plan a trip", "Travel"),
    ("Find a bus to Jaipur", "Travel"),
    ("Book a cab to the airport", "Travel"),
    ("Show available flights", "Travel"),
    ("Travel next weekend", "Travel"),
    ("I need travel tickets", "Travel"),
    ("Find places to visit", "Travel"),
    ("Reserve my hotel", "Travel"),
    ("Book accommodation", "Travel"),
    ("Search travel options", "Travel"),

    # 💸 Refund
    ("I need to return my order", "Refund"),
    ("Can I get a refund?", "Refund"),
    ("Refund this item please", "Refund"),
    ("I'd like to cancel my purchase", "Refund"),
    ("Please return my money", "Refund"),
    ("This product isn't good, refund it", "Refund"),
    ("I want to send this back", "Refund"),
    ("Cancel my payment", "Refund"),
    ("Refund my purchase", "Refund"),
    ("Can you reverse this order?", "Refund"),
    ("I'd like my money back", "Refund"),
    ("Undo my purchase", "Refund"),
    ("Cancel this transaction", "Refund"),
    ("Please refund me", "Refund"),
    ("I don't need this anymore", "Refund"),
    ("Take back this product", "Refund"),
    ("Reverse my payment", "Refund"),
    ("Return this package", "Refund"),
    ("Can you cancel the order?", "Refund"),
    ("Refund requested", "Refund"),

    # 🎵 Music
    ("Play something relaxing", "Music"),
    ("Start playing songs", "Music"),
    ("Skip this track", "Music"),
    ("Play my workout playlist", "Music"),
    ("Turn the music up", "Music"),
    ("Turn the volume down", "Music"),
    ("Play some hip hop", "Music"),
    ("Play classical music", "Music"),
    ("I want to hear music", "Music"),
    ("Stop the song", "Music"),
    ("Continue playing", "Music"),
    ("Play the next track", "Music"),
    ("Replay this song", "Music"),
    ("Random songs please", "Music"),
    ("Play happy music", "Music"),
    ("Play sad songs", "Music"),
    ("Start my playlist", "Music"),
    ("Can you play music?", "Music"),
    ("Play instrumental music", "Music"),
    ("Change the song", "Music"),

    # ⏰ Alarm
    ("Set a wake-up alarm", "Alarm"),
    ("Wake me tomorrow at 8", "Alarm"),
    ("Alarm in one hour", "Alarm"),
    ("Create a reminder alarm", "Alarm"),
    ("Turn on my alarm", "Alarm"),
    ("Disable all alarms", "Alarm"),
    ("Set an alarm for 5:30", "Alarm"),
    ("Wake me up in 20 minutes", "Alarm"),
    ("Alarm for this evening", "Alarm"),
    ("Set an alarm every weekday", "Alarm"),
    ("I need an alarm", "Alarm"),
    ("Make an alarm for tomorrow", "Alarm"),
    ("Schedule an alarm", "Alarm"),
    ("Remove tomorrow's alarm", "Alarm"),
    ("Cancel every alarm", "Alarm"),
    ("Alarm after two hours", "Alarm"),
    ("Wake me at noon", "Alarm"),
    ("Morning wake-up reminder", "Alarm"),
    ("Create a morning alarm", "Alarm"),
    ("Set my alarm", "Alarm"),

    # 🧮 Calculator
    ("What's 45 plus 55?", "Calculator"),
    ("Calculate 18 x 7", "Calculator"),
    ("What's 144 divided by 12?", "Calculator"),
    ("Add 99 and 101", "Calculator"),
    ("Subtract 350 from 1000", "Calculator"),
    ("Multiply 15 by 15", "Calculator"),
    ("What is 8 squared?", "Calculator"),
    ("Find the square root of 49", "Calculator"),
    ("Solve 56 plus 29", "Calculator"),
    ("Do this calculation", "Calculator"),
    ("Can you calculate this?", "Calculator"),
    ("How much is 77 minus 22?", "Calculator"),
    ("What's the answer to 9 x 11?", "Calculator"),
    ("Calculate 125 divided by 5", "Calculator"),
    ("Add these values", "Calculator"),
    ("Math problem", "Calculator"),
    ("Find the result", "Calculator"),
    ("What's 200 minus 75?", "Calculator"),
    ("Compute 14 times 9", "Calculator"),
    ("Calculate this expression", "Calculator"),

    # ☀️ Weather
    ("Will it be hot tomorrow?", "Weather"),
    ("Is it raining outside?", "Weather"),
    ("Tell me today's forecast", "Weather"),
    ("How's the weather?", "Weather"),
    ("What's the temperature?", "Weather"),
    ("Is it going to rain this evening?", "Weather"),
    ("Will it be sunny tomorrow?", "Weather"),
    ("Check today's weather", "Weather"),
    ("What's the forecast for Monday?", "Weather"),
    ("How cold is it outside?", "Weather"),
    ("Will I need a jacket?", "Weather"),
    ("Is there a storm coming?", "Weather"),
    ("Show this week's weather", "Weather"),
    ("Weather report", "Weather"),
    ("How warm is it today?", "Weather"),
    ("Tell me if it'll rain", "Weather"),
    ("Forecast for my city", "Weather"),
    ("Is today a good day to go out?", "Weather"),
    ("What's the climate like today?", "Weather"),
    ("Give me the weather update", "Weather"),

    # 📰 News
    ("Tell me the latest news", "News"),
    ("Any breaking stories?", "News"),
    ("What's new today?", "News"),
    ("Give me today's headlines", "News"),
    ("Show world headlines", "News"),
    ("Any sports updates?", "News"),
    ("Technology updates", "News"),
    ("What's happening around the world?", "News"),
    ("Tell me business news", "News"),
    ("Any news about AI?", "News"),
    ("Show me current events", "News"),
    ("Latest political updates", "News"),
    ("Entertainment headlines", "News"),
    ("What's trending today?", "News"),
    ("Science headlines", "News"),
    ("Health updates", "News"),
    ("What's in the news?", "News"),
    ("Tell me the top stories", "News"),
    ("Give me news updates", "News"),
    ("Any important news today?", "News"),

    # 👋 Greeting
    ("Hey, good morning!", "Greeting"),
    ("Hi, what's up?", "Greeting"),
    ("Hello, can we talk?", "Greeting"),
    ("Good evening!", "Greeting"),
    ("Hey friend", "Greeting"),
    ("Hi, nice to see you again", "Greeting"),
    ("Hope you're doing great", "Greeting"),
    ("Hello, how's everything?", "Greeting"),
    ("Hey, how are things?", "Greeting"),
    ("Good to see you again", "Greeting"),
    ("Hi, are you free?", "Greeting"),
    ("Hey, can you help?", "Greeting"),
    ("Hello there!", "Greeting"),
    ("Morning!", "Greeting"),
    ("Evening!", "Greeting"),
    ("Hey, hope you're well", "Greeting"),
    ("Hi buddy", "Greeting"),
    ("Hello, nice meeting you", "Greeting"),
    ("Hey there, AI", "Greeting"),
    ("Hi, how's your day?", "Greeting"),

    # 🍕 Food
    ("Can you get me dinner?", "Food"),
    ("I'm really hungry", "Food"),
    ("Let's eat pizza tonight", "Food"),
    ("Bring me a burger", "Food"),
    ("I'd love some sushi", "Food"),
    ("Can you order biryani for me?", "Food"),
    ("I'm in the mood for pasta", "Food"),
    ("Let's order something tasty", "Food"),
    ("Can I have a sandwich?", "Food"),
    ("Find a pizza place", "Food"),
    ("Order a large pizza", "Food"),
    ("I want something spicy", "Food"),
    ("Get me some momos", "Food"),
    ("Find a good restaurant", "Food"),
    ("Can we order dessert?", "Food"),
    ("I feel like eating Chinese food", "Food"),
    ("Order coffee for me", "Food"),
    ("Bring me a cold drink", "Food"),
    ("I'd like to eat now", "Food"),
    ("Can you buy food?", "Food"),

    # ✈️ Travel
    ("Help me book my flight", "Travel"),
    ("I need a hotel room", "Travel"),
    ("Find flights for next week", "Travel"),
    ("Show flights to Chennai", "Travel"),
    ("Reserve a hotel near the airport", "Travel"),
    ("Book tickets for my trip", "Travel"),
    ("Find me a train", "Travel"),
    ("I need a bus ticket", "Travel"),
    ("Plan my holiday", "Travel"),
    ("Find tourist places", "Travel"),
    ("Book my stay", "Travel"),
    ("Search for vacation packages", "Travel"),
    ("I want to go to Goa", "Travel"),
    ("Book travel for tomorrow", "Travel"),
    ("Reserve a flight seat", "Travel"),
    ("Find nearby hotels", "Travel"),
    ("Show travel offers", "Travel"),
    ("Get me a flight", "Travel"),
    ("Help me travel to Hyderabad", "Travel"),
    ("Book a weekend trip", "Travel"),

    # 💸 Refund
    ("I received the wrong item", "Refund"),
    ("I want to return this product", "Refund"),
    ("This isn't what I ordered", "Refund"),
    ("Please cancel my purchase", "Refund"),
    ("I need a full refund", "Refund"),
    ("Refund this order immediately", "Refund"),
    ("Return my payment", "Refund"),
    ("I don't like this product", "Refund"),
    ("I'd like to send this back", "Refund"),
    ("Can you process my refund?", "Refund"),
    ("Take this order back", "Refund"),
    ("Reverse this transaction", "Refund"),
    ("Please cancel the payment", "Refund"),
    ("The item is damaged, refund it", "Refund"),
    ("I'd like to return my package", "Refund"),
    ("Refund my purchase please", "Refund"),
    ("Cancel everything", "Refund"),
    ("This order should be refunded", "Refund"),
    ("I no longer need this order", "Refund"),
    ("Please give me my money back", "Refund"),

    # 🎵 Music
    ("Play something upbeat", "Music"),
    ("Put on some chill music", "Music"),
    ("Start my favorite playlist", "Music"),
    ("Can you skip this song?", "Music"),
    ("Play dance music", "Music"),
    ("I want to listen to songs", "Music"),
    ("Turn up the sound", "Music"),
    ("Reduce the music volume", "Music"),
    ("Play old songs", "Music"),
    ("Play romantic music", "Music"),
    ("Start playing again", "Music"),
    ("Pause the current song", "Music"),
    ("Play the previous track", "Music"),
    ("Play some relaxing tunes", "Music"),
    ("Switch to another song", "Music"),
    ("Can you play jazz?", "Music"),
    ("Play something energetic", "Music"),
    ("Resume the playlist", "Music"),
    ("Play my liked songs", "Music"),
    ("Turn off the music", "Music"),

    # ⏰ Alarm
    ("Wake me up tomorrow", "Alarm"),
    ("Set an alarm for 9 AM", "Alarm"),
    ("Alarm after one hour", "Alarm"),
    ("Remind me to wake up", "Alarm"),
    ("Set a bedtime alarm", "Alarm"),
    ("Create an alarm for Friday", "Alarm"),
    ("Turn off tomorrow's alarm", "Alarm"),
    ("Wake me at 5:45", "Alarm"),
    ("Set an evening alarm", "Alarm"),
    ("Make sure I wake up", "Alarm"),
    ("Alarm in 15 minutes", "Alarm"),
    ("Set my morning reminder", "Alarm"),
    ("Remove all alarms", "Alarm"),
    ("Schedule a wake-up call", "Alarm"),
    ("Alarm at midnight", "Alarm"),
    ("Wake me before sunrise", "Alarm"),
    ("Create a repeating alarm", "Alarm"),
    ("Cancel the morning alarm", "Alarm"),
    ("Set an alarm every day", "Alarm"),
    ("I need to wake up early", "Alarm"),

    # 🧮 Calculator
    ("Calculate 32 plus 48", "Calculator"),
    ("What's 500 divided by 25?", "Calculator"),
    ("Multiply 13 by 7", "Calculator"),
    ("Subtract 15 from 90", "Calculator"),
    ("Add 250 and 450", "Calculator"),
    ("How much is 16 times 16?", "Calculator"),
    ("Find 75 minus 18", "Calculator"),
    ("What's 90 plus 10?", "Calculator"),
    ("Calculate 1200 divided by 12", "Calculator"),
    ("Solve this equation", "Calculator"),
    ("Do a quick calculation", "Calculator"),
    ("What's the total?", "Calculator"),
    ("Find the sum", "Calculator"),
    ("What's the difference?", "Calculator"),
    ("Can you solve this math problem?", "Calculator"),
    ("Calculate this for me", "Calculator"),
    ("How much is 44 plus 56?", "Calculator"),
    ("Multiply these values", "Calculator"),
    ("Find the product", "Calculator"),
    ("Work out this calculation", "Calculator"),

    # ☀️ Weather
    ("Will it be cold tonight?", "Weather"),
    ("What's today's weather like?", "Weather"),
    ("Do I need an umbrella today?", "Weather"),
    ("Is it warm outside?", "Weather"),
    ("Check tomorrow's forecast", "Weather"),
    ("What's the weather this weekend?", "Weather"),
    ("Will it be windy today?", "Weather"),
    ("Is there any rain expected?", "Weather"),
    ("How's the weather in Bangalore?", "Weather"),
    ("Show today's forecast", "Weather"),
    ("What's outside weather?", "Weather"),
    ("Will it be cloudy later?", "Weather"),
    ("Give me today's temperature", "Weather"),
    ("How's the climate outside?", "Weather"),
    ("Should I carry a jacket?", "Weather"),
    ("Is it freezing outside?", "Weather"),
    ("What's the weather update?", "Weather"),
    ("Tell me tomorrow's weather", "Weather"),
    ("Any chance of rain today?", "Weather"),
    ("Forecast for tonight", "Weather"),

    # 📰 News
    ("What's the latest update?", "News"),
    ("Tell me today's top news", "News"),
    ("Any world news?", "News"),
    ("Show me technology headlines", "News"),
    ("What's happening in sports?", "News"),
    ("Give me finance news", "News"),
    ("Any updates on the economy?", "News"),
    ("Tell me entertainment news", "News"),
    ("Show AI headlines", "News"),
    ("What's happening in India?", "News"),
    ("Latest science updates", "News"),
    ("Any health headlines?", "News"),
    ("Read today's news", "News"),
    ("What's making headlines?", "News"),
    ("Give me the news summary", "News"),
    ("Show current headlines", "News"),
    ("Any important updates?", "News"),
    ("Tell me what's happening", "News"),
    ("Latest world events", "News"),
    ("Catch me up on the news", "News"),

]
